version: '3'

services:
  client:
    container_name: phorkit-docz
    build:
      context: ./
      dockerfile: ./.docker/docz/Dockerfile
    image: phorkit-docz
    env_file:
      - .env
    ports:
      - ${PUBLIC_DOCZ_PORT}:80
    networks:
      - phorknet

networks:
  phorknet:
    driver: bridge
